In [2]:
# https://medium.com/@nrk25693/how-to-add-your-conda-environment-to-your-jupyter-notebook-in-just-4-steps-abeab8b8d084
import torch

## Why floating point numbers

<!-- From Deep Learning with PyTorch -->
Since floating-point numbers are the way a network deals with information, we need a
way to encode real-world data of the kind we want to process into something digestible
by a network and then decode the output back to something we can understand and
use for our purpose.


## What are tensors?

In the context of deep learning, tensors are the generalization of vectors and matrices to an arbitrary number of dimensions, aka multi-dimensional array.

Include image here.

In [5]:
from IPython.core.debugger import set_trace

def f(x):
    res = x + x
    set_trace()
    return res

x = torch.randn(1, 10)
f(x)

> <ipython-input-5-0bfb02c7733d>(6)f()
      4     res = x + x
      5     set_trace()
----> 6     return res
      7 
      8 x = torch.randn(1, 10)



ipdb>  res


tensor([[ 3.2584,  1.9709,  1.5012, -1.5466,  0.0933, -2.2792, -0.3819, -0.8717,
         -2.1653, -1.4487]])


ipdb>  exit


BdbQuit: 

# References
- Twitter: https://twitter.com/PyTorch 
- Forum: https://discuss.pytorch.org/
- Tutorials: https://pytorch.org/tutorials/
- Examples: https://github.com/pytorch/examples
- API Reference: https://pytorch.org/docs/stable/index.html
- Torchvision: https://pytorch.org/docs/stable/torchvision/index.html
- PyTorch Text: https://github.com/pytorch/text
- PyTorch Audio: https://github.com/pytorch/audio
- AllenNLP: https://allennlp.org/
- Object detection/segmentation: https://github.com/facebookresearch/maskrcnn-benchmark
- Facebook AI Research Sequence-to-Sequence Toolkit written in PyTorch: https://github.com/pytorch/fairseq
- FastAI http://www.fast.ai/
- Stanford CS230 Deep Learning notes https://cs230-stanford.github.io

In [6]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [7]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
X = torch.rand((3,3))
X

tensor([[0.1919, 0.0398, 0.3730],
        [0.6104, 0.8873, 0.4701],
        [0.1108, 0.7016, 0.3781]])

In [18]:
X.shape

torch.Size([3, 3])

In [23]:
torch.inverse(X) @ X 

tensor([[ 1.0000e+00, -1.5200e-07, -1.0447e-07],
        [ 3.8447e-08,  1.0000e+00, -3.6762e-08],
        [-3.9081e-09,  5.2456e-08,  1.0000e+00]])

In [22]:
torch.inverse(X) * X

tensor([[ 0.0094,  0.0838, -0.9950],
        [-0.9319,  0.2369,  0.5519],
        [ 0.3122, -0.7806,  0.4716]])

@TODO: find the difference between * and @ operator