In [1]:
# https://medium.com/@nrk25693/how-to-add-your-conda-environment-to-your-jupyter-notebook-in-just-4-steps-abeab8b8d084
import torch

## Why floating point numbers

<!-- From Deep Learning with PyTorch -->
Since floating-point numbers are the way a network deals with information, we need a
way to encode real-world data of the kind we want to process into something digestible
by a network and then decode the output back to something we can understand and
use for our purpose.


## What are tensors?

In the context of deep learning, tensors are the generalization of vectors and matrices to an arbitrary number of dimensions, aka multi-dimensional array.

Include image here.

In [2]:
from IPython.core.debugger import set_trace

def f(x):
    res = x + x
    set_trace()
    return res

x = torch.randn(1, 10)
f(x)

> <ipython-input-2-0bfb02c7733d>(6)f()
      4     res = x + x
      5     set_trace()
----> 6     return res
      7 
      8 x = torch.randn(1, 10)

ipdb> x
tensor([[-1.9401, -0.6922, -0.1051,  0.5972, -1.1804, -0.3269,  0.2342,  0.0211,
         -0.8859,  1.5354]])
ipdb> res
tensor([[-3.8802, -1.3845, -0.2102,  1.1945, -2.3608, -0.6537,  0.4684,  0.0423,
         -1.7718,  3.0708]])
ipdb> quit


BdbQuit: 

# References
- Twitter: https://twitter.com/PyTorch 
- Forum: https://discuss.pytorch.org/
- Tutorials: https://pytorch.org/tutorials/
- Examples: https://github.com/pytorch/examples
- API Reference: https://pytorch.org/docs/stable/index.html
- Torchvision: https://pytorch.org/docs/stable/torchvision/index.html
- PyTorch Text: https://github.com/pytorch/text
- PyTorch Audio: https://github.com/pytorch/audio
- AllenNLP: https://allennlp.org/
- Object detection/segmentation: https://github.com/facebookresearch/maskrcnn-benchmark
- Facebook AI Research Sequence-to-Sequence Toolkit written in PyTorch: https://github.com/pytorch/fairseq
- FastAI http://www.fast.ai/
- Stanford CS230 Deep Learning notes https://cs230-stanford.github.io

In [5]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [7]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
X = torch.rand((3,3))
X

tensor([[0.1919, 0.0398, 0.3730],
        [0.6104, 0.8873, 0.4701],
        [0.1108, 0.7016, 0.3781]])

In [18]:
X.shape

torch.Size([3, 3])

In [23]:
torch.inverse(X) @ X 

tensor([[ 1.0000e+00, -1.5200e-07, -1.0447e-07],
        [ 3.8447e-08,  1.0000e+00, -3.6762e-08],
        [-3.9081e-09,  5.2456e-08,  1.0000e+00]])

In [22]:
torch.inverse(X) * X

tensor([[ 0.0094,  0.0838, -0.9950],
        [-0.9319,  0.2369,  0.5519],
        [ 0.3122, -0.7806,  0.4716]])

@TODO: find the difference between * and @ operator

# Initializing tensors

In [3]:
## Directly from data
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
## From a numpy array
np_array = np.array(data)
x_np_data = torch.from_numpy(np_array)
x_np_data

tensor([[1, 2],
        [3, 4]])

In [11]:
## From another tensor
x_ones = torch.ones_like(x_data) # same datatype as x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Ones Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[0.6026, 0.0363],
        [0.4467, 0.6216]]) 



More PyTorch operations and examples here:
    https://pytorch.org/docs/stable/torch.html

In [19]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f"Moved to cuda if available: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Moved to cuda if available: cuda:0


In [20]:
tensor

tensor([[0.2020, 0.8425, 0.4596, 0.3089],
        [0.7423, 0.4075, 0.2407, 0.7623],
        [0.9373, 0.5680, 0.2076, 0.8598]], device='cuda:0')

In [21]:
tensor.add(1)

tensor([[1.2020, 1.8425, 1.4596, 1.3089],
        [1.7423, 1.4075, 1.2407, 1.7623],
        [1.9373, 1.5680, 1.2076, 1.8598]], device='cuda:0')

In [22]:
tensor

tensor([[0.2020, 0.8425, 0.4596, 0.3089],
        [0.7423, 0.4075, 0.2407, 0.7623],
        [0.9373, 0.5680, 0.2076, 0.8598]], device='cuda:0')

In [23]:
# Operations with "_" mutates a tensor in place
tensor.add_(1)

tensor([[1.2020, 1.8425, 1.4596, 1.3089],
        [1.7423, 1.4075, 1.2407, 1.7623],
        [1.9373, 1.5680, 1.2076, 1.8598]], device='cuda:0')

In [24]:
tensor

tensor([[1.2020, 1.8425, 1.4596, 1.3089],
        [1.7423, 1.4075, 1.2407, 1.7623],
        [1.9373, 1.5680, 1.2076, 1.8598]], device='cuda:0')

# Autograd

In [25]:
import torchvision

In [27]:
dir(torchvision.models)

['AlexNet',
 'DenseNet',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'Inception3',
 'InceptionOutputs',
 'MNASNet',
 'MobileNetV2',
 'ResNet',
 'ShuffleNetV2',
 'SqueezeNet',
 'VGG',
 '_GoogLeNetOutputs',
 '_InceptionOutputs',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_utils',
 'alexnet',
 'densenet',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'detection',
 'googlenet',
 'inception',
 'inception_v3',
 'mnasnet',
 'mnasnet0_5',
 'mnasnet0_75',
 'mnasnet1_0',
 'mnasnet1_3',
 'mobilenet',
 'mobilenet_v2',
 'quantization',
 'resnet',
 'resnet101',
 'resnet152',
 'resnet18',
 'resnet34',
 'resnet50',
 'resnext101_32x8d',
 'resnext50_32x4d',
 'segmentation',
 'shufflenet_v2_x0_5',
 'shufflenet_v2_x1_0',
 'shufflenet_v2_x1_5',
 'shufflenet_v2_x2_0',
 'shufflenetv2',
 'squeezenet',
 'squeezenet1_0',
 'squeezenet1_1',
 'utils',
 'vgg',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vg

`Tensor`s now automatically track autograd, no need to track yourself.

# PyTorch, Gradient Descent and GPU

In [28]:
!pip install sklearn

You should consider upgrading via the '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/python -m pip install --upgrade pip' command.


In [ ]:
from sklearn.datasets import make_regression

n = 1
n_samples = 100

